name: Rebuild nightly

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
    - uses: satak/webrequest-action@master
      with:
        url: ${{secrets.DOCKER_REBUILD_URL}}
        method: POST
